/**
 * Stories named after their cast. A story whose title is still one of these follows its
 * characters: the server renames it when characters are added or removed, and the client's
 * Edit Story modal previews that rename as the cast changes.
 */

/**
 * Generate an auto-title from a list of character names.
 * Returns a title like "A Story with Alice" or "A Story with Alice and Bob"
 * or "A Story with Alice, Bob, and Charlie" for 3+ characters.
 */
export function generateAutoTitle(characterNames) {
  if (characterNames.length === 0) {
    return 'Untitled Story';
  } else if (characterNames.length === 1) {
    return `A Story with ${characterNames[0]}`;
  } else if (characterNames.length === 2) {
    return `A Story with ${characterNames[0]} and ${characterNames[1]}`;
  } else {
    const allButLast = characterNames.slice(0, -1);
    const last = characterNames[characterNames.length - 1];
    return `A Story with ${allButLast.join(', ')}, and ${last}`;
  }
}

/**
 * Check if a title is an auto-generated title that should be updated
 * when characters change.
 */
export function isAutoGeneratedTitle(title) {
  if (!title) return false;
  return (
    title === 'Untitled Story' ||
    title.startsWith('Story with ') ||
    title.startsWith('A Story with ')
  );
}
