/**
 * Stories and chats named after their cast. One whose title is still one of these follows its
 * characters: the server renames it when characters are added or removed, and the client's
 * Edit Story modal previews that rename as the cast changes.
 */

/** "Alice", "Alice and Bob", or "Alice, Bob, and Charlie". */
export function joinNames(names) {
  if (names.length <= 1) return names[0] ?? '';
  if (names.length === 2) return `${names[0]} and ${names[1]}`;
  return `${names.slice(0, -1).join(', ')}, and ${names.at(-1)}`;
}

/**
 * Generate an auto-title from a list of character names.
 * Returns a title like "A Story with Alice" or "A Story with Alice and Bob"
 * or "A Story with Alice, Bob, and Charlie" for 3+ characters.
 */
export function generateAutoTitle(characterNames) {
  if (characterNames.length === 0) return 'Untitled Story';
  return `A Story with ${joinNames(characterNames)}`;
}

/**
 * Check if a title is an auto-generated title that should be updated
 * when characters change.
 */
export function isAutoGeneratedTitle(title) {
  if (!title) return false;
  return (
    title === 'Untitled Story' ||
    title.startsWith('Story with ') ||
    title.startsWith('A Story with ')
  );
}

/** A chat's title from its characters: "Chat with Alice and Bob", or "Untitled Chat". */
export function generateChatTitle(characterNames) {
  return characterNames.length > 0 ? `Chat with ${joinNames(characterNames)}` : 'Untitled Chat';
}

/** Check if a chat's title is still named after its characters. */
export function isAutoChatTitle(title) {
  if (!title) return false;
  return title === 'Untitled Chat' || title.startsWith('Chat with ');
}
